### ISSUE TITLE
Go To Definition/References Not Working

### ISSUE THREAD

**Issue by nwant** [johnmutuma5/coc-apex#11]
I am receiving the following error when I try to go to definition or references:

<img width="749" alt="coc-nvim_jump-def-error" src="https://user-images.githubusercontent.com/12848268/147857880-6c3ac534-a6cd-4f5f-9622-6d96e8ea13d1.png">

I have tried invoking these commands for functions and classes declared in the same file and different files in my sfdx project folder structure, and I continue to receive the error regardless.

The autocomplete for the Apex language is working for me, so it appears `coc-apex` is installed and using the language server properly, at least for this particular functionality.

Here are my mapping to the coc commands:

```vim
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```
Perhaps I am overlooking something. Do you have any suggestions?

Thank you!

**Comment by johnmutuma5** [comment]
This could be a problem with filetype. Check your filetype it should be apexcode

**Comment by nwant** [comment]
Hi @johnmutuma5 , thanks for the response!

Yes, that was the problem; I was using `filetype=apex` as I was using that filetype for syntax highlighting. I changed the filetype to `apexcode` across the board and both Go To Definition and References are working; however, now I am finding when I successfully use `jumpDefinition`, the filetype stops being recognized in the buffer for some reason, so I have to reset it manually every time (I'm using neovim 0.6.1, if that matters)...but that's separate issue, I suppose.

Appreciate the help!

**Comment by johnmutuma5** [comment]
Yes certainly a different issue @nwant, but I think I could help with that. You might want to set an auto command to set the filetype.

I have something along these lines in [my vimrc](https://github.com/johnmutuma5/vim-editor/blob/3df131e1d58caecf1f9277441447b6d5e3e50457/.vimrc#L321)

```vim
augroup set_filetype
  :autocmd!
  :autocmd BufEnter *.apex,*.cls :set filetype=apexcode " Salesforce files
augroup END
```

That way I don't have to set the filetype manually for .apex and .cls files as the auto-command does it on BufEnter events.
